### PR TITLE
push on pypi each time a commit is pushed to main branch

### PR DESCRIPTION
**Pull request by AurelienJaquier**

### CODE REVIEW

**Review by wvangeit — APPROVED** [review]

**Comment by AurelienJaquier** [comment]
Looks like PyPi does not accept scm version :(

**Comment by wvangeit** [comment]
Ok, whatever works is fine for me ;-)

**Comment by anilbey** [comment]
This should do it. From the docs:

> no-local-version: | omits local version, useful e.g. because pypi does not support it




```
    use_scm_version={
        'version_scheme': 'python-simplified-semver',
        'local_scheme': 'no-local-version'
    },
```

**Comment by wvangeit** [comment]
This still seems to be creating dev releases though.
https://pypi.org/project/currentscape/1.0.4.dev6/
We need a full release at each commit.

**Comment by anilbey** [comment]
Ah yes semver requires us to tag the releases (the stable versions). `pip install` will install the stable versions by default, not the dev versions.

**Comment by wvangeit** [comment]
It wouldn't hurt if the github action could create a tag and release for each PR merge commit. 
That way Zenodo would also build a new DOI etc.

**Comment by wvangeit** [comment]
Maybe something like https://github.com/marketplace/actions/auto-release
but then without using a specific matching pattern, just whenever a PR is merged.

**Comment by anilbey** [comment]
> So anyway around that?

I don't know, we need a way of auto tagging probably.

It is preference I guess but I am more inclined to think it is powerful to be able to control which version will be stable and which to be the dev. E.g. we could tell Zenodo to build the DOI only on the stable versions to prevent unexpected effects of dev versions. Again it's preference, so your call :)

**Comment by wvangeit** [comment]
So imo their should be now dev versions in the main branch. They could be in a dev branch.
All these versioning in main should be completely automated, so that devs don't have to bother manually releasing etc.

So for @AurelienJaquier , please switch to versioneer. Unless we find another quick solution.

**Comment by wvangeit** [comment]
(again, I'm also ok with a solution that tags/releases each commit on main, we probably need the latter anyway, even with versioneer)

**Pull request merged**
